name: "Nick's bots üçë"

on: workflow_dispatch

jobs:
  post_chambers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'poetry'
      - name: Post to The Chambers Pot
        run: python chambers.py
        env:
          BSKY_BASE_URL: ${{ secrets.BSKY_BASE_URL }}
          CHAMBERS_BSKY_HANDLE: ${{ secrets.CHAMBERS_BSKY_HANDLE }}
          CHAMBERS_BSKY_PASSWORD: ${{ secrets.CHAMBERS_BSKY_PASSWORD }}
          CHAMBERS_MASTO_ACCESS_TOKEN: ${{ secrets.CHAMBERS_MASTO_ACCESS_TOKEN }}
          LYTTON_BSKY_HANDLE: ${{ secrets.LYTTON_BSKY_HANDLE }}
          LYTTON_BSKY_PASSWORD: ${{ secrets.LYTTON_BSKY_PASSWORD }}
          LYTTON_MASTO_ACCESS_TOKEN: ${{ secrets.LYTTON_MASTO_ACCESS_TOKEN }}
          MASTO_BASE_URL: ${{ secrets.MASTO_BASE_URL }}
          PODRACING_BSKY_HANDLE: ${{ secrets.PODRACING_BSKY_HANDLE }}
          PODRACING_BSKY_PASSWORD: ${{ secrets.PODRACING_BSKY_PASSWORD }}
          PODRACING_MASTO_ACCESS_TOKEN: ${{ secrets.PODRACING_MASTO_ACCESS_TOKEN }}
          WORDNIK_API_KEY: ${{ secrets.WORDNIK_API_KEY }}
